title: "Animal Volunteer Aid"
description: "A practical knowledge base for pet owners and zoo volunteers. Note: This is not a substitute for professional veterinary advice."

baseurl: "/animal-care"
url: "https://phoenixway.github.io"

# ВИКОРИСТОВУЄМО НАДІЙНИЙ МЕТОД ЗАВАНТАЖЕННЯ ТЕМИ
remote_theme: just-the-docs/just-the-docs

# Налаштування для just-the-docs
color_scheme: light # Можна змінити на dark
search_enabled: true # Вмикає поле пошуку по сайту

# Плагіни
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-default-layout
  
